### ISSUE TITLE
App crashed on trying get user id

### ISSUE THREAD

**Issue by gstuczynski** [1uphealth/1upwebapp#8]
App crashed when i trying to log in

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/gstuczynski/repos/1upwebapp/oneup.js:76:23)
    at Request.self.callback (/Users/gstuczynski/repos/1upwebapp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/gstuczynski/repos/1upwebapp/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/gstuczynski/repos/1upwebapp/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Problem is in this function 
```
function getOneUpUserId (email, callback) {
  let getUrl = `${USER_API_URL}/user-management/v1/user?client_id=${ONEUP_DEMOWEBAPPLOCAL_CLIENTID}&client_secret=${ONEUP_DEMOWEBAPPLOCAL_CLIENTSECRET}&app_user_id=${email}`
  console.log(getUrl)
  request.get(getUrl, function(error, response, body) {
    console.log('body',response.statusCode,body,'----', getUrl)
    let jsbody = JSON.parse(body)
      callback(jsbody.oneup_user_id)
  })
}
```

returned body is html so it can't be parsed in this way, moreover i cant find there properties 'oneup_user_id' so i don't know how to fix it.
Same problem occured when i  trying to get system_id following this guide https://1up.health/dev/doc/quick-connect,

**Comment by liam1uphealth** [comment]
Can you make sure that your ONEUP_DEMOWEBAPPLOCAL_CLIENTSECRET and ONEUP_DEMOWEBAPPLOCAL_CLIENTID are set and accurate? I believe this error is thrown in response to that.

Let us know if you have any more questions!
